import type { LibraryConfig } from "../types";

export const webcnLibrary: LibraryConfig = {
  name: "webcn Landing Page",
  description:
    "Landing page components for webcn - Webflow full-stack React component framework",
  id: "webcn-landing",

  // Component metadata for library viewer
  componentMetadata: [
    {
      id: "webcn-architecture",
      name: "webcn Architecture",
      description: "Animated diagram showing the full-stack architecture from Webflow to database",
      category: "Landing",
      props: [
        {
          name: "badgeText",
          type: "Text",
          description: "Text displayed in the badge above the section title",
          defaultValue: "Architecture",
          required: false,
        },
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the section",
          defaultValue: "Enterprise-Grade Full-Stack Architecture",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the section heading",
          defaultValue: "From Webflow to database, built with security and scalability in mind",
          required: false,
        },
        {
          name: "showBadge",
          type: "Boolean",
          description: "Toggle the badge visibility above the section title",
          defaultValue: true,
          required: false,
        },
      ],
      usageExample: `<ArchitectureSectionWrapper badgeText="Architecture" sectionTitle="Full-Stack Architecture" showBadge={true} />`,
      tags: ["architecture", "landing", "diagram"],
      filePath: "src/libraries/webcn/components/ArchitectureSection.webflow.tsx",
    },
    {
      id: "webcn-blog-cta",
      name: "webcn Blog CTA",
      description: "Call-to-action card linking to technical blog post",
      category: "Landing",
      props: [
        {
          name: "title",
          type: "Text",
          description: "Main heading for the CTA card",
          defaultValue: "Deep Dive: Building Full-Stack Webflow Apps",
          required: false,
        },
        {
          name: "description",
          type: "Text",
          description: "Description text for the CTA",
          defaultValue: "Read our technical breakdown of how webcn brings React's full ecosystem to Webflow, complete with authentication, databases, and more.",
          required: false,
        },
        {
          name: "buttonText",
          type: "Text",
          description: "Text for the CTA button",
          defaultValue: "Read the Blog Post",
          required: false,
        },
      ],
      usageExample: `<BlogCTAWrapper title="Technical Deep Dive" description="Learn how webcn works" buttonText="Read More" />`,
      tags: ["cta", "landing", "blog"],
      filePath: "src/libraries/webcn/components/BlogCTA.webflow.tsx",
    },
    {
      id: "webcn-component-card",
      name: "Component Card",
      description: "Individual component card for collection lists - displays component preview, name, category, and description",
      category: "Landing",
      props: [
        {
          name: "previewImage",
          type: "Text",
          description: "URL to preview image (leave empty for placeholder)",
          defaultValue: "",
          required: false,
        },
        {
          name: "componentName",
          type: "Text",
          description: "Name of the component",
          defaultValue: "Component Name",
          required: false,
        },
        {
          name: "category",
          type: "Text",
          description: "Category tag (e.g., UI, Full-Stack, Interactive)",
          defaultValue: "UI",
          required: false,
        },
        {
          name: "description",
          type: "RichText",
          description: "Brief description of what the component does",
          defaultValue: "Component description",
          required: false,
        },
        {
          name: "link",
          type: "Link",
          description: "Link to component details or demo (includes URL, target, and preload options)",
          defaultValue: undefined,
          required: false,
        },
        {
          name: "buttonText",
          type: "Text",
          description: "Text displayed on the action button",
          defaultValue: "View Component",
          required: false,
        },
        {
          name: "isFullStack",
          type: "Boolean",
          description: "If true, uses primary badge color; if false, uses secondary",
          defaultValue: false,
          required: false,
        },
      ],
      usageExample: `<ComponentCardWrapper componentName="Auth Component" category="Full-Stack" description="User authentication" isFullStack={true} />`,
      tags: ["card", "component", "collection"],
      filePath: "src/libraries/webcn/components/ComponentCard.webflow.tsx",
    },
    {
      id: "webcn-demo-section",
      name: "webcn Demo Section",
      description: "Demo section showcasing the blogflow full-stack application",
      category: "Landing",
      props: [
        {
          name: "badgeText",
          type: "Text",
          description: "Text displayed in the badge",
          defaultValue: "Live Demo",
          required: false,
        },
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the demo section",
          defaultValue: "See It In Action",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the section heading",
          defaultValue: "blogflow: A full-stack collaborative blog built entirely with webcn components",
          required: false,
        },
        {
          name: "demoTitle",
          type: "Text",
          description: "Title of the demo application",
          defaultValue: "blogflow",
          required: false,
        },
        {
          name: "demoDescription",
          type: "Text",
          description: "Description of the demo application",
          defaultValue: "A fully functional blogging platform showcasing the power of webcn. Users can register, authenticate, create posts, and collaborate — all running natively within Webflow using code components.",
          required: false,
        },
        {
          name: "ctaButtonText",
          type: "Text",
          description: "Text for the call-to-action button",
          defaultValue: "Try blogflow Demo",
          required: false,
        },
        {
          name: "ctaLink",
          type: "Link",
          description: "Link for the call-to-action button",
          defaultValue: { href: "/demo", target: "_self" },
          required: false,
        },
        {
          name: "showBadge",
          type: "Boolean",
          description: "Toggle visibility of the badge",
          defaultValue: true,
          required: false,
        },
      ],
      usageExample: `<DemoSectionWrapper badgeText="Live Demo" sectionTitle="See It In Action" demoTitle="blogflow" ctaLink={{ href: "/demo", target: "_self" }} showBadge={true} />`,
      tags: ["demo", "landing", "showcase"],
      filePath: "src/libraries/webcn/components/DemoSection.webflow.tsx",
    },
    {
      id: "webcn-features",
      name: "webcn Features",
      description: "Feature grid showcasing key features with icons and descriptions",
      category: "Landing",
      props: [
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the features section",
          defaultValue: "More Than Just Components",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the section heading",
          defaultValue: "A complete framework for building production applications in Webflow",
          required: false,
        },
      ],
      usageExample: `<FeaturesWrapper sectionTitle="Key Features" sectionSubtitle="Everything you need" />`,
      tags: ["features", "landing", "grid"],
      filePath: "src/libraries/webcn/components/Features.webflow.tsx",
    },
    {
      id: "webcn-features-summary",
      name: "Features Summary",
      description: "High-level features summary section highlighting modular, typesafe, and authenticated architecture",
      category: "Landing",
      props: [
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the features summary section",
          defaultValue: "Built for Modern Web Development",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the main heading",
          defaultValue: "Everything you need to build production-ready applications in Webflow",
          required: false,
        },
        {
          name: "ctaText",
          type: "Text",
          description: "Text displayed on the call-to-action button",
          defaultValue: "Explore All Features",
          required: false,
        },
        {
          name: "ctaLink",
          type: "Text",
          description: "URL to navigate to when CTA button is clicked",
          defaultValue: "/lander/webcn/features",
          required: false,
        },
      ],
      usageExample: `<FeaturesSummaryWrapper sectionTitle="Modern Development" ctaText="Learn More" ctaLink="/features" />`,
      tags: ["features", "landing", "summary"],
      filePath: "src/libraries/webcn/components/FeaturesSummary.webflow.tsx",
    },
    {
      id: "webcn-footer",
      name: "webcn Footer",
      description: "Footer section with brand, links, and social icons",
      category: "Navigation",
      props: [
        {
          name: "brandText",
          type: "Text",
          description: "Brand name displayed in the footer",
          defaultValue: "webcn",
          required: false,
        },
        {
          name: "brandSubtext",
          type: "Text",
          description: "Description text below the brand name",
          defaultValue: "Full-stack React components for Webflow",
          required: false,
        },
        {
          name: "builderName",
          type: "Text",
          description: "Name of the builder/creator to display in footer",
          defaultValue: "UZO LAB",
          required: false,
        },
        {
          name: "builderUrl",
          type: "Text",
          description: "URL to link to the builder/creator website",
          defaultValue: "https://uzolab-template.webflow.io",
          required: false,
        },
        {
          name: "hackathonText",
          type: "Text",
          description: "Text displayed on second line of footer credits",
          defaultValue: "for Webflow x Contra Hackathon",
          required: false,
        },
        {
          name: "githubUrl",
          type: "Text",
          description: "URL for the GitHub link",
          defaultValue: "https://github.com",
          required: false,
        },
        {
          name: "twitterUrl",
          type: "Text",
          description: "URL for the Twitter link",
          defaultValue: "https://twitter.com",
          required: false,
        },
      ],
      usageExample: `<FooterWrapper brandText="webcn" brandSubtext="Full-stack components" githubUrl="https://github.com/..." />`,
      tags: ["footer", "landing", "navigation"],
      filePath: "src/libraries/webcn/components/Footer.webflow.tsx",
    },
    {
      id: "webcn-hero",
      name: "webcn Hero",
      description: "Hero section with gradient backgrounds, badge, and CTA buttons",
      category: "Landing",
      props: [
        {
          name: "badgeText",
          type: "Text",
          description: "Text displayed in the top badge",
          defaultValue: "Webflow × Contra Hackathon Entry",
          required: false,
        },
        {
          name: "title",
          type: "Text",
          description: "Main heading text",
          defaultValue: "webcn",
          required: false,
        },
        {
          name: "subtitle",
          type: "Text",
          description: "Subtitle text below the main title",
          defaultValue: "Full-stack React components for Webflow",
          required: false,
        },
        {
          name: "description",
          type: "Text",
          description: "Detailed description text",
          defaultValue: "Leverage Webflow's new code components feature to build production-ready applications. Drop in authentication, databases, and complex UI — all running natively in Webflow.",
          required: false,
        },
        {
          name: "primaryCtaText",
          type: "Text",
          description: "Text for the primary call-to-action button",
          defaultValue: "Browse Components",
          required: false,
        },
        {
          name: "primaryCtaUrl",
          type: "Text",
          description: "URL or anchor link for primary button (e.g., #components, /page, https://...)",
          defaultValue: "#components",
          required: false,
        },
        {
          name: "secondaryCtaText",
          type: "Text",
          description: "Text for the secondary call-to-action button",
          defaultValue: "View Demo",
          required: false,
        },
        {
          name: "secondaryCtaUrl",
          type: "Text",
          description: "URL or anchor link for secondary button (e.g., #demo, /page, https://...)",
          defaultValue: "#demo",
          required: false,
        },
        {
          name: "showBadge",
          type: "Boolean",
          description: "Toggle visibility of the top badge",
          defaultValue: true,
          required: false,
        },
        {
          name: "showTechStack",
          type: "Boolean",
          description: "Toggle visibility of the technology stack section",
          defaultValue: true,
          required: false,
        },
        {
          name: "showBackground",
          type: "Boolean",
          description: "Toggle the DarkVeil animated background effect",
          defaultValue: true,
          required: false,
        },
        {
          name: "hueShift",
          type: "Number",
          description: "Adjust the color hue of the background (0-360 degrees)",
          defaultValue: 100,
          required: false,
        },
        {
          name: "noiseIntensity",
          type: "Number",
          description: "Amount of visual noise/grain effect (0-1)",
          defaultValue: 0.2,
          required: false,
        },
        {
          name: "scanlineIntensity",
          type: "Number",
          description: "Strength of scanline effect (0-1)",
          defaultValue: 0.4,
          required: false,
        },
        {
          name: "speed",
          type: "Number",
          description: "Speed of the background animation (0-5)",
          defaultValue: 1.2,
          required: false,
        },
        {
          name: "scanlineFrequency",
          type: "Number",
          description: "Frequency/density of scanlines (0-2)",
          defaultValue: 0.6,
          required: false,
        },
        {
          name: "warpAmount",
          type: "Number",
          description: "Amount of warping/distortion effect (0-1)",
          defaultValue: 0.4,
          required: false,
        },
        {
          name: "resolutionScale",
          type: "Number",
          description: "Rendering resolution (0.5-2, lower = better performance)",
          defaultValue: 1,
          required: false,
        },
      ],
      usageExample: `<HeroWrapper title="webcn" subtitle="Full-stack components" showBadge={true} showBackground={true} />`,
      tags: ["hero", "landing", "cta"],
      filePath: "src/libraries/webcn/components/Hero.webflow.tsx",
    },
    {
      id: "webcn-hub-dashboard",
      name: "webcn Hub Dashboard",
      description: "Interactive dashboard preview for managing libraries and connecting services",
      category: "Landing",
      props: [
        {
          name: "badgeText",
          type: "Text",
          description: "Text displayed in the badge above the section title",
          defaultValue: "Management Hub",
          required: false,
        },
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the section",
          defaultValue: "Control Center for Your Stack",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the section heading",
          defaultValue: "Connect services, install libraries, and configure your backend — all from one dashboard",
          required: false,
        },
        {
          name: "showBadge",
          type: "Boolean",
          description: "Toggle the badge visibility above the section title",
          defaultValue: true,
          required: false,
        },
        {
          name: "hubTitle",
          type: "Text",
          description: "Title displayed in the dashboard header",
          defaultValue: "webcn Hub",
          required: false,
        },
        {
          name: "projectName",
          type: "Text",
          description: "Project name displayed in the dashboard header",
          defaultValue: "my-webflow-app",
          required: false,
        },
        {
          name: "statusText",
          type: "Text",
          description: "Status text displayed in the badge (e.g., Live, Development, Staging)",
          defaultValue: "Live",
          required: false,
        },
      ],
      usageExample: `<HubDashboardSectionWrapper badgeText="Dashboard" sectionTitle="Control Center" hubTitle="webcn Hub" showBadge={true} />`,
      tags: ["dashboard", "landing", "management"],
      filePath: "src/libraries/webcn/components/HubDashboardSection.webflow.tsx",
    },
    {
      id: "webcn-hub-dashboard-section-image",
      name: "webcn Hub Dashboard (Image)",
      description: "Image-based variant of the management dashboard. Replaces interactive UI with a configurable screenshot or GIF.",
      category: "Landing",
      props: [
        {
          name: "image",
          type: "Image",
          description: "Select a screenshot or GIF from your Webflow asset library showing the hub dashboard",
          defaultValue: undefined,
          required: false,
        },
        {
          name: "badgeText",
          type: "Text",
          description: "Text displayed in the badge above the section title",
          defaultValue: "Management Hub",
          required: false,
        },
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the section",
          defaultValue: "Control Center for Your Stack",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the section heading",
          defaultValue: "Connect services, install libraries, and configure your backend — all from one dashboard",
          required: false,
        },
        {
          name: "showBadge",
          type: "Boolean",
          description: "Toggle the badge visibility above the section title",
          defaultValue: true,
          required: false,
        },
        {
          name: "feature1Title",
          type: "Text",
          description: "Title for the first feature below the dashboard",
          defaultValue: "One-Click Setup",
          required: false,
        },
        {
          name: "feature1Description",
          type: "Text",
          description: "Description for the first feature",
          defaultValue: "Connect your accounts and deploy in minutes",
          required: false,
        },
        {
          name: "feature2Title",
          type: "Text",
          description: "Title for the second feature below the dashboard",
          defaultValue: "Modular Libraries",
          required: false,
        },
        {
          name: "feature2Description",
          type: "Text",
          description: "Description for the second feature",
          defaultValue: "Install only what you need, when you need it",
          required: false,
        },
        {
          name: "feature3Title",
          type: "Text",
          description: "Title for the third feature below the dashboard",
          defaultValue: "Full Control",
          required: false,
        },
        {
          name: "feature3Description",
          type: "Text",
          description: "Description for the third feature",
          defaultValue: "Configure every aspect of your deployment",
          required: false,
        },
      ],
      usageExample: `<HubDashboardSectionImageWrapper image={assetImage} sectionTitle="Dashboard" feature1Title="Fast Setup" />`,
      tags: ["dashboard", "landing", "image"],
      filePath: "src/libraries/webcn/components/HubDashboardSectionImage.webflow.tsx",
    },
    {
      id: "webcn-navbar",
      name: "webcn Navbar",
      description: "Fixed navigation bar with logo, configurable links, and GitHub button",
      category: "Navigation",
      props: [
        {
          name: "logoText",
          type: "Text",
          description: "Text displayed in the logo",
          defaultValue: "webcn",
          required: false,
        },
        {
          name: "githubUrl",
          type: "Text",
          description: "URL for the GitHub link",
          defaultValue: "https://github.com",
          required: false,
        },
        {
          name: "ctaButtonText",
          type: "Text",
          description: "Text for the call-to-action button",
          defaultValue: "Get Started",
          required: false,
        },
        {
          name: "ctaButtonUrl",
          type: "Text",
          description: "URL for the call-to-action button",
          defaultValue: "#get-started",
          required: false,
        },
        {
          name: "showGithubLink",
          type: "Boolean",
          description: "Toggle visibility of the GitHub icon link",
          defaultValue: true,
          required: false,
        },
        {
          name: "link1Label",
          type: "Text",
          description: "Text for the first navigation link",
          defaultValue: "Features",
          required: false,
        },
        {
          name: "link1Url",
          type: "Text",
          description: "URL for the first navigation link",
          defaultValue: "#features",
          required: false,
        },
        {
          name: "showLink1",
          type: "Boolean",
          description: "Toggle visibility of the first navigation link",
          defaultValue: true,
          required: false,
        },
        {
          name: "link2Label",
          type: "Text",
          description: "Text for the second navigation link",
          defaultValue: "Components",
          required: false,
        },
        {
          name: "link2Url",
          type: "Text",
          description: "URL for the second navigation link",
          defaultValue: "#components",
          required: false,
        },
        {
          name: "showLink2",
          type: "Boolean",
          description: "Toggle visibility of the second navigation link",
          defaultValue: true,
          required: false,
        },
        {
          name: "link3Label",
          type: "Text",
          description: "Text for the third navigation link",
          defaultValue: "Demo",
          required: false,
        },
        {
          name: "link3Url",
          type: "Text",
          description: "URL for the third navigation link",
          defaultValue: "#demo",
          required: false,
        },
        {
          name: "showLink3",
          type: "Boolean",
          description: "Toggle visibility of the third navigation link",
          defaultValue: true,
          required: false,
        },
        {
          name: "link4Label",
          type: "Text",
          description: "Text for the fourth navigation link",
          defaultValue: "Story",
          required: false,
        },
        {
          name: "link4Url",
          type: "Text",
          description: "URL for the fourth navigation link",
          defaultValue: "#story",
          required: false,
        },
        {
          name: "showLink4",
          type: "Boolean",
          description: "Toggle visibility of the fourth navigation link",
          defaultValue: true,
          required: false,
        },
      ],
      usageExample: `<NavbarWrapper logoText="webcn" link1Label="Features" link1Url="#features" showGithubLink={true} />`,
      tags: ["navigation", "navbar", "landing"],
      filePath: "src/libraries/webcn/components/Navbar.webflow.tsx",
    },
    {
      id: "webcn-story-section",
      name: "webcn Story Section",
      description: "Story section explaining the hackathon challenge, vision, and impact",
      category: "Landing",
      props: [
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the story section",
          defaultValue: "The Hackathon Story",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the section heading",
          defaultValue: "Why we're building a framework instead of \"just another website\"",
          required: false,
        },
        {
          name: "feature1Title",
          type: "Text",
          description: "Title for the first feature (Challenge)",
          defaultValue: "The Challenge",
          required: false,
        },
        {
          name: "feature1Description",
          type: "Text",
          description: "Description text for the first feature",
          defaultValue: "Webflow's new Code Components feature unlocked something powerful: the ability to bring React's ecosystem into Webflow. But nobody had built the infrastructure to make it truly useful.",
          required: false,
        },
        {
          name: "feature2Title",
          type: "Text",
          description: "Title for the second feature (Vision)",
          defaultValue: "The Vision",
          required: false,
        },
        {
          name: "feature2Description",
          type: "Text",
          description: "Description text for the second feature",
          defaultValue: "Instead of a traditional landing page submission, we're shipping a complete full-stack framework. Real authentication, databases, and server logic—all running natively in Webflow.",
          required: false,
        },
        {
          name: "feature3Title",
          type: "Text",
          description: "Title for the third feature (Impact)",
          defaultValue: "The Impact",
          required: false,
        },
        {
          name: "feature3Description",
          type: "Text",
          description: "Description text for the third feature",
          defaultValue: "webcn isn't just for this hackathon. It's a foundation for developers to build production-ready apps in Webflow, pushing the platform beyond its traditional boundaries.",
          required: false,
        },
      ],
      usageExample: `<StorySectionWrapper sectionTitle="Our Story" feature1Title="Challenge" feature2Title="Vision" feature3Title="Impact" />`,
      tags: ["story", "landing", "features"],
      filePath: "src/libraries/webcn/components/StorySection.webflow.tsx",
    },
    {
      id: "webcn-styling-control",
      name: "webcn Styling Control",
      description: "Interactive demo showcasing design system integration with shadcn/ui and tweakcn",
      category: "Landing",
      props: [
        {
          name: "badgeText",
          type: "Text",
          description: "Text displayed in the badge above the section title",
          defaultValue: "Design System",
          required: false,
        },
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the section",
          defaultValue: "Complete Styling Control",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the section heading",
          defaultValue: "Full design system integration with shadcn/ui core tokens and libraries like tweakcn",
          required: false,
        },
        {
          name: "feature1Title",
          type: "Text",
          description: "Title for the first feature",
          defaultValue: "CSS Variables",
          required: false,
        },
        {
          name: "feature1Description",
          type: "Text",
          description: "Description for the first feature",
          defaultValue: "All components use CSS custom properties that automatically adapt to your design system. Change once, update everywhere.",
          required: false,
        },
        {
          name: "feature2Title",
          type: "Text",
          description: "Title for the second feature",
          defaultValue: "shadcn/ui Compatible",
          required: false,
        },
        {
          name: "feature2Description",
          type: "Text",
          description: "Description for the second feature",
          defaultValue: "Built on the same design tokens as shadcn/ui. Drop in any shadcn component and it just works with your theme.",
          required: false,
        },
        {
          name: "feature3Title",
          type: "Text",
          description: "Title for the third feature",
          defaultValue: "tweakcn Ready",
          required: false,
        },
        {
          name: "feature3Description",
          type: "Text",
          description: "Description for the third feature",
          defaultValue: "Fully compatible with tweakcn and other design tools. Adjust colors, spacing, and typography with zero code changes.",
          required: false,
        },
        {
          name: "showBadge",
          type: "Boolean",
          description: "Toggle the badge visibility above the section title",
          defaultValue: true,
          required: false,
        },
      ],
      usageExample: `<StylingControlSectionWrapper badgeText="Design System" sectionTitle="Styling Control" showBadge={true} />`,
      tags: ["styling", "landing", "design-system"],
      filePath: "src/libraries/webcn/components/StylingControlSection.webflow.tsx",
    },
    {
      id: "webcn-styling-control-section-image",
      name: "webcn Styling Control (Image)",
      description: "Image-based variant showcasing design system integration. Replaces live theme preview with a configurable GIF or static image.",
      category: "Landing",
      props: [
        {
          name: "image",
          type: "Image",
          description: "Select an image or GIF from your Webflow asset library to showcase the styling/theming demo",
          defaultValue: undefined,
          required: false,
        },
        {
          name: "badgeText",
          type: "Text",
          description: "Text displayed in the badge above the section title",
          defaultValue: "Design System",
          required: false,
        },
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the section",
          defaultValue: "Complete Styling Control",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the section heading",
          defaultValue: "Full design system integration with shadcn/ui core tokens and libraries like tweakcn",
          required: false,
        },
        {
          name: "feature1Title",
          type: "Text",
          description: "Title for the first feature",
          defaultValue: "CSS Variables",
          required: false,
        },
        {
          name: "feature1Description",
          type: "Text",
          description: "Description for the first feature",
          defaultValue: "All components use CSS custom properties that automatically adapt to your design system. Change once, update everywhere.",
          required: false,
        },
        {
          name: "feature2Title",
          type: "Text",
          description: "Title for the second feature",
          defaultValue: "shadcn/ui Compatible",
          required: false,
        },
        {
          name: "feature2Description",
          type: "Text",
          description: "Description for the second feature",
          defaultValue: "Built on the same design tokens as shadcn/ui. Drop in any shadcn component and it just works with your theme.",
          required: false,
        },
        {
          name: "feature3Title",
          type: "Text",
          description: "Title for the third feature",
          defaultValue: "tweakcn Ready",
          required: false,
        },
        {
          name: "feature3Description",
          type: "Text",
          description: "Description for the third feature",
          defaultValue: "Fully compatible with tweakcn and other design tools. Adjust colors, spacing, and typography with zero code changes.",
          required: false,
        },
        {
          name: "showBadge",
          type: "Boolean",
          description: "Toggle the badge visibility above the section title",
          defaultValue: true,
          required: false,
        },
      ],
      usageExample: `<StylingControlSectionImageWrapper image={assetImage} sectionTitle="Styling Demo" showBadge={true} />`,
      tags: ["styling", "landing", "image"],
      filePath: "src/libraries/webcn/components/StylingControlSectionImage.webflow.tsx",
    },
    {
      id: "webcn-video-section",
      name: "webcn Video Section",
      description: "Video section with YouTube embed - click thumbnail to play",
      category: "Landing",
      props: [
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the video section",
          defaultValue: "See webcn in Action",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the section heading",
          defaultValue: "Watch how we're reimagining what's possible in Webflow",
          required: false,
        },
        {
          name: "videoUrl",
          type: "Text",
          description: "YouTube video URL (supports youtube.com/watch?v=, youtu.be/, or video ID)",
          defaultValue: "",
          required: false,
        },
      ],
      usageExample: `<VideoSectionWrapper sectionTitle="Watch Demo" videoUrl="https://youtube.com/watch?v=..." />`,
      tags: ["video", "landing", "youtube"],
      filePath: "src/libraries/webcn/components/VideoSection.webflow.tsx",
    },
    {
      id: "webcn-waitlist",
      name: "webcn Waitlist",
      description: "Waitlist capture section that imports from the waitlist library (tests cross-library bundling)",
      category: "Landing",
      props: [
        {
          name: "badgeText",
          type: "Text",
          description: "Text displayed in the badge above the section title",
          defaultValue: "Join the Waitlist",
          required: false,
        },
        {
          name: "sectionTitle",
          type: "Text",
          description: "Main heading for the waitlist section",
          defaultValue: "Be Among the First",
          required: false,
        },
        {
          name: "sectionSubtitle",
          type: "Text",
          description: "Subtitle text below the section heading",
          defaultValue: "Get early access to webcn and be part of the future of Webflow development",
          required: false,
        },
        {
          name: "formTitle",
          type: "Text",
          description: "Title for the waitlist form card",
          defaultValue: "Reserve Your Spot",
          required: false,
        },
        {
          name: "formSubtitle",
          type: "Text",
          description: "Subtitle for the waitlist form card",
          defaultValue: "Join thousands of developers already on the list",
          required: false,
        },
        {
          name: "buttonText",
          type: "Text",
          description: "Text displayed on the submit button",
          defaultValue: "Join Waitlist",
          required: false,
        },
        {
          name: "successMessage",
          type: "Text",
          description: "Message shown after successful signup",
          defaultValue: "🎉 You're in! We'll notify you when we launch.",
          required: false,
        },
        {
          name: "showNameField",
          type: "Boolean",
          description: "Display optional name input field",
          defaultValue: true,
          required: false,
        },
        {
          name: "showBadge",
          type: "Boolean",
          description: "Toggle the badge visibility above the section title",
          defaultValue: true,
          required: false,
        },
      ],
      usageExample: `<WaitlistSectionWrapper badgeText="Early Access" sectionTitle="Join Waitlist" showBadge={true} />`,
      tags: ["waitlist", "landing", "cta"],
      filePath: "src/libraries/webcn/components/WaitlistSection.webflow.tsx",
    },
  ],

  // Environment variables exposed to this library
  env: {
    // Add any environment variables needed for the landing page
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  },

  // Deployment configuration
  deploy: {
    enabled: true, // Auto-deploy on merge to main
    workspaceToken: process.env.WEBFLOW_WORKSPACE_API_TOKEN,
  },
};
